'use client'
import Link from 'next/link'
import type {PostMeta} from '../../lib/blog'
import {career,projects} from '../../lib/portfolio/data'
import {perspectives,type Perspective} from '../../lib/portfolio/perspectives'
import {useAstral} from './Shell'
export default function HomeStory({posts}:{posts:PostMeta[]}){
 const {perspective,choose,openGuide}=useAstral(),story=perspectives[perspective]
 const careerSection=<section className="astral-chapter" data-chapter="career" id="career"><p className="folio-eyebrow">01 / The career thread · 2018 — present</p><h2>{perspective==='hiring'?'Experience that grows with responsibility.':'One decision becomes the foundation for the next.'}</h2><div className="astral-career">{career.map((role,i)=><article key={role.id}><div><span className="folio-eyebrow">{role.dates}</span><h3>{role.company}</h3><p>{role.role}</p></div><div><h4>{role.theme}</h4><p>{role.narrative}</p><Link href={`/profile#${role.id}`}>Explore the role ↗</Link></div><span className="astral-index">0{5-i}</span></article>)}</div><Link href="/profile" className="folio-btn">Full career & practice ↗</Link></section>
 const workSection=<section className="astral-chapter" data-chapter="work" id="work"><p className="folio-eyebrow">02 / Independent work · five explorations</p><h2>{perspective==='ai'?'Intelligence needs a method.':'Ideas made inspectable.'}</h2><p className="astral-lead">A connected workspace. Tools for AI-assisted engineering. Experiments with clear boundaries.</p><div className="astral-projects">{projects.map(project=><Link href={`/work/${project.slug}`} key={project.slug}><span className="folio-eyebrow">{project.number} / {project.status}</span><h3>{project.name}</h3><p>{project.line}</p><div className="astral-project-layers" aria-hidden="true">{project.stages.map((stage,i)=><span key={stage}><small>0{i+1}</small>{stage}</span>)}</div><p>{project.description}</p><span>Purpose → Approach → Trade-off ↗</span></Link>)}</div></section>
 return <div className="astral-home"><section className="astral-arrival" data-chapter="arrival"><p className="folio-eyebrow">Animesh Basak / Lead Engineer</p><h1>A different way<br/>to know <em>the builder.</em></h1><p className="astral-lead">Frontend systems and architecture. AI-assisted backend and React Native contributions. Independent ideas, built with care.</p><button className="astral-question" onClick={openGuide}>What would you like to know about me? <span>↗</span></button><div className="astral-choices">{Object.entries(perspectives).map(([key,p])=><a href="#story" key={key} onClick={()=>choose(key as Perspective)} aria-current={key===perspective?'true':undefined}>{p.label} ↗</a>)}</div><a className="astral-browse" href="#story">Or explore the whole story ↓</a></section><section className="astral-story-intro" id="story"><p className="folio-eyebrow">Your perspective / {story.label}</p><h2>{story.title}</h2><p className="astral-lead">{story.intro}</p></section>{perspective==='hiring'?<>{careerSection}{workSection}</>:<>{workSection}{careerSection}</>}<section className="astral-chapter" data-chapter="writing"><p className="folio-eyebrow">03 / Thinking in public</p><h2>The notes behind the work.</h2><div className="astral-writing">{posts.slice(0,4).map(post=><Link key={post.slug} href={`/blog/${post.slug}`}><span>{post.date}</span><h3>{post.title}</h3><span>↗</span></Link>)}</div><Link className="folio-btn" href="/blog">All writing ↗</Link></section><section className="astral-chapter astral-connect" data-chapter="contact"><p className="folio-eyebrow">04 / The next chapter</p><h2>Something worth<br/>building, together.</h2><p className="astral-lead">Let’s talk about the problems, the team and the engineering behind the experience.</p><Link className="folio-btn" href="/contact">Start a conversation ↗</Link><a className="astral-browse" href="/resume-public.pdf">Take the original résumé ↗</a></section></div>
}
