'use client'
import Link from 'next/link'
import {useSearchParams} from 'next/navigation'
import {useEffect,useRef,useState} from 'react'
import {compare,searchCounterexample,DEFAULT_REQUIREMENTS,DEFAULT_SCENARIO,type Requirements,type Scenario,type Strategy,type CounterexampleSearch} from '../../lib/proof/engine'
import {createReplay,serializeReplay,parseReplay,REPLAY_STORAGE_KEY,type Replay} from '../../lib/proof/replay'
import {sceneState} from './scene/state'
import Icon from './Icon'
import s from './studio.module.css'
const names={'cache-first':'Show it now','network-first':'Verify it first'}
const verdicts={'cache-first':'Showing it now fits.','network-first':'Verifying it first fits.',both:'Both approaches fit.',neither:'Neither approach fits.'}
export default function ProofStudio(){
 const params=useSearchParams(),origin=params.get('from')||'/work',safeOrigin=/^\/(?:work(?:\/[a-z0-9-]+)?|profile|blog(?:\/[a-z0-9-]+)?|contact)?$/.test(origin)?origin:'/work'
 const[requirements,setRequirements]=useState<Requirements>({...DEFAULT_REQUIREMENTS}),[scenario,setScenario]=useState<Scenario>({...DEFAULT_SCENARIO}),[step,setStep]=useState(0),[strategy,setStrategy]=useState<Strategy>('cache-first'),[search,setSearch]=useState<CounterexampleSearch|null>(null),[replay,setReplay]=useState<Replay|null>(null),[saved,setSaved]=useState<Replay|null>(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[guideMode,setGuideMode]=useState('Authored guide'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const workspace=useRef<HTMLDivElement>(null),previousStep=useRef(0),requestId=useRef(0)
 const controller=useRef<AbortController|null>(null),comparison=compare(requirements,scenario),replayResult=replay?compare(replay.requirements,replay.scenario):comparison,duration=Math.max(1,replayResult.scenario.responseMs,replayResult.requirements.deadlineMs)
 useEffect(()=>{try{const raw=localStorage.getItem(REPLAY_STORAGE_KEY);if(raw)setSaved(parseReplay(raw))}catch{}return()=>controller.current?.abort()},[])
 useEffect(()=>{if(previousStep.current===step)return;previousStep.current=step;if(matchMedia('(max-width:760px)').matches)workspace.current?.scrollIntoView({block:'start',behavior:'instant'})},[step])
 useEffect(()=>{sceneState.branch=replayResult.verdict==='network-first'?1:replayResult.verdict==='cache-first'?-1:0},[replayResult.verdict])
 useEffect(()=>{sceneState.replay=time/duration},[time,duration])
 useEffect(()=>{if(!playing)return;let frame=0,start:number|undefined;const initial=time;const tick=(now:number)=>{start??=now;const next=Math.min(duration,initial+(now-start)*.5);setTime(next);if(next<duration)frame=requestAnimationFrame(tick);else setPlaying(false)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing,duration])
 function change(next:Requirements,nextScenario=scenario){requestId.current++;controller.current?.abort();setBusy(false);setRequirements(next);setScenario(nextScenario);setSearch(null);setReplay(null);setPlaying(false);setTime(0);setAnswer('');setNotice('')}
 function challenge(){const found=searchCounterexample(strategy,requirements);setSearch(found);setStep(2);setReplay(null);setPlaying(false)}
 function startReplay(value:Replay){requestId.current++;controller.current?.abort();setBusy(false);setAnswer('');setReplay(value);setTime(0);setPlaying(false);setStep(2);try{localStorage.setItem(REPLAY_STORAGE_KEY,serializeReplay(value));setSaved(value);setNotice('Replay saved on this device.')}catch{setNotice('Replay ready. This browser could not save it.')}}
 async function ask(event:React.FormEvent){event.preventDefault();if(!question.trim()||busy)return;controller.current?.abort();const c=new AbortController(),id=++requestId.current;controller.current=c;const timer=setTimeout(()=>c.abort(),9000);setBusy(true);setAnswer('');try{const response=await fetch('/api/proof',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,requirements:replayResult.requirements,scenario:replayResult.scenario}),signal:c.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'Guide unavailable.');if(id!==requestId.current)return;setAnswer(data.answer+(data.clarification?` ${data.clarification}`:''));setGuideMode(data.mode==='ai'?'AI-selected guide':data.mode==='scope'?'Scope guide':'Authored guide')}catch{if(id!==requestId.current)return;setGuideMode('Local fallback');setAnswer(`${verdicts[replayResult.verdict]} The saved copy appears at 0 ms and is ${replayResult.scenario.cacheAgeSeconds} seconds old. The verified copy appears at ${replayResult.scenario.responseMs} ms. Compare those with your waiting and freshness limits below.`)}finally{clearTimeout(timer);if(id===requestId.current)setBusy(false)}}
 return <section className={s.page}><Link className={s.back} href={safeOrigin} data-proof-return>← Return to {safeOrigin==='/'?'the story':safeOrigin.startsWith('/blog/')?'the article':safeOrigin.startsWith('/work/')?'the project':safeOrigin.slice(1)}</Link>
  <header className={s.header}><div><span className="folio-eyebrow">PROOF STUDIO / EXPERIMENT 001</span><h1>Change one thing.<br/><span>See what changes.</span></h1></div><p>A reading board. Two approaches.<br/>Your requirements decide what fits.<small>INDEPENDENT, SYNTHETIC EXPERIMENT</small></p></header>
  <nav className={s.steps} aria-label="Experiment steps">{['Set requirements','Compare evidence','Challenge & replay'].map((label,i)=><button key={label} type="button" aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><small>0{i+1}</small>{label}</button>)}</nav>
  <div ref={workspace} className={s.workspace} data-step={step}>
   <aside className={`${s.requirements} folio-panel`}><span className="folio-eyebrow">01 / WHAT MATTERS TO YOU?</span><h2>Set the brief.</h2><p>These requirements apply to the first copy a visitor sees.</p>
    <label className={s.field}>Maximum waiting time<output>{requirements.deadlineMs} ms</output><input aria-label="Maximum waiting time" type="range" min="0" max="2000" step="50" value={requirements.deadlineMs} onChange={e=>change({...requirements,deadlineMs:Number(e.target.value)})}/><span>Immediate <span>2 seconds</span></span></label>
    <label className={s.field}>Freshness requirement<select value={requirements.maxAgeSeconds===null?'verified':String(requirements.maxAgeSeconds)} onChange={e=>change({...requirements,maxAgeSeconds:e.target.value==='verified'?null:Number(e.target.value)})}><option value="120">Up to 2 minutes old</option><option value="45">Up to 45 seconds old</option><option value="0">0 seconds old</option><option value="verified">Verified during this visit</option></select></label>
    <div className={s.presets}><span className="folio-eyebrow">TRY A DIFFERENT BRIEF</span><button onClick={()=>change({deadlineMs:150,maxAgeSeconds:null})}>Fast + verified ↗</button><button onClick={()=>change({deadlineMs:1000,maxAgeSeconds:null})}>Allow time to verify ↗</button><button onClick={()=>change({...DEFAULT_REQUIREMENTS},{...DEFAULT_SCENARIO})}>Reset the experiment ↺</button></div>
    <details className={s.scenario}><summary>Adjust the scenario</summary><label>Saved copy age <input aria-label="Saved copy age in seconds" type="number" min="0" max="86400" value={scenario.cacheAgeSeconds} onChange={e=>change(requirements,{...scenario,cacheAgeSeconds:Math.max(0,Math.min(86400,Number(e.target.value)||0))})}/> seconds</label><label>Response time <input aria-label="Response time in milliseconds" type="number" min="0" max="60000" value={scenario.responseMs} onChange={e=>change(requirements,{...scenario,responseMs:Math.max(0,Math.min(60000,Number(e.target.value)||0))})}/> ms</label></details>
    <button className={`folio-btn ${s.mobileNext}`} data-variant="primary" onClick={()=>setStep(1)}>Compare both approaches <Icon name="arrow"/></button>
   </aside>
   <div className={s.evidence}><div className={s.briefSummary}><span>YOUR BRIEF · {requirements.deadlineMs}ms maximum wait · {requirements.maxAgeSeconds===null?'Verified this visit':`${requirements.maxAgeSeconds}s maximum age`}</span><button onClick={()=>setStep(0)}>Edit requirements ↗</button></div><div className={s.verdict} role="status"><span className="folio-eyebrow">02 / THE VERDICT</span><h2>{verdicts[comparison.verdict]}</h2><p>{comparison.verdict==='neither'?'Both approaches miss at least one requirement. Change the brief or reconsider the strategies.':comparison.verdict==='both'?'Both meet this brief in this scenario. Search for a failure before choosing.':'The evidence below shows exactly which requirements pass at first display.'}</p></div>
    <div className={s.cards}>{(['cache-first','network-first'] as Strategy[]).map((id,i)=>{const r=comparison.strategies[id];return <article key={id} id={`result:${id}`} className={`${s.strategy} folio-panel`} data-pass={r.passes}><div className={s.strategyTop}><small>APPROACH {i===0?'A':'B'}</small><span>{r.passes?'FITS THIS BRIEF':'MISSES A REQUIREMENT'}</span></div><h3>{names[id]}</h3><p>{i===0?'Show the saved copy. Refresh in the background.':'Wait for a verified copy. Then display it.'}</p><div className={s.readingBoard}><span>READING BOARD <i/></span><b>Interfaces & their decisions</b><div/><div/><small>{r.verifiedThisVisit?'Verified this visit':`Last verified ${r.displayAgeSeconds}s ago`}</small></div><dl><div><dt>First display</dt><dd>{r.displayAtMs} ms</dd></div><div><dt>Waiting limit</dt><dd data-pass={r.predicates.waiting}>{r.predicates.waiting?'Pass':'Fail'}</dd></div><div><dt>Freshness</dt><dd data-pass={r.predicates.freshness}>{r.predicates.freshness?'Pass':'Fail'}</dd></div></dl></article>})}</div>
    <button className={`folio-btn ${s.mobileNext}`} data-variant="primary" onClick={()=>setStep(2)}>Now challenge a choice <Icon name="arrow"/></button>
   </div>
   <section className={s.challenge}><div className={s.challengeIntro}><span className="folio-eyebrow">03 / FIND WHERE THIS FAILS</span><h2>A passing scenario<br/>isn’t the whole story.</h2><p>Search nine combinations of saved-copy age and response time for the first failure of your chosen approach.</p></div><div className={`${s.challengeControl} folio-panel`}><label>Challenge this approach<select value={strategy} onChange={e=>{setStrategy(e.target.value as Strategy);setSearch(null)}}><option value="cache-first">A · Show it now</option><option value="network-first">B · Verify it first</option></select></label><button className="folio-btn" data-variant="primary" onClick={challenge}>Find a counterexample <Icon name="arrow"/></button><small>AGES: 0 / 45 / 121s · RESPONSES: 80 / 800 / 1500ms</small></div>
    {search&&<div className={s.searchResult} role="status"><span className="folio-eyebrow">{search.counterexample?'COUNTEREXAMPLE FOUND':'SEARCH COMPLETE'}</span><h3>{search.message}</h3><p>{search.testedScenarios.length} of {search.totalScenarios} scenarios tested.{!search.counterexample?' This bounded search is not a proof that the approach always works.':''}</p>{search.counterexample&&<><p>Saved copy: <b>{search.counterexample.scenario.cacheAgeSeconds}s old</b> · Response: <b>{search.counterexample.scenario.responseMs}ms</b></p><button className="folio-btn" onClick={()=>startReplay(createReplay(requirements,search.counterexample!.scenario,strategy))}>Replay this failure <Icon name="arrow"/></button></>}</div>}
    <div className={s.replayActions}><button onClick={()=>startReplay(createReplay(requirements,scenario,strategy))}>Replay the current scenario ↗</button>{saved&&<button onClick={()=>startReplay(saved)}>Restore saved replay ↺</button>}</div>
    {replay&&<section id="proof-replay" className={`${s.replay} folio-panel`}><span className="folio-eyebrow">DETERMINISTIC REPLAY / V1</span><h3>The decision, moment by moment.</h3><p>Virtual time. Saved settings reproduce the same events.</p><p className={s.replayBrief}>REPLAY BRIEF · {replay.requirements.deadlineMs}ms maximum wait · {replay.requirements.maxAgeSeconds===null?'Verified this visit':`${replay.requirements.maxAgeSeconds}s maximum age`}<br/>SCENARIO · {replay.scenario.cacheAgeSeconds}s saved-copy age · {replay.scenario.responseMs}ms response<br/>CHALLENGED APPROACH · {names[replay.strategy]}</p><div className={s.replayBoards}>{(['cache-first','network-first'] as Strategy[]).map(id=>{const verified=time>=replayResult.scenario.responseMs,waiting=id==='network-first'&&!verified;return <article key={id}><small>{names[id]}</small><strong>{waiting?'Waiting for verification…':'Interfaces & their decisions'}</strong><p>{waiting?'Nothing displayed yet':verified?'Verified copy visible':`Saved copy visible · ${replayResult.scenario.cacheAgeSeconds}s old`}</p><span className={s.replayProgress} style={{transform:`scaleX(${Math.min(1,time/Math.max(1,replayResult.scenario.responseMs))})`}}/><b>{replayResult.strategies[id].passes?'Fits this replay brief':`First display fails: ${replayResult.strategies[id].failedPredicates.join(' + ')}`}</b></article>})}</div><div className={s.transport}><button className="folio-btn" onClick={()=>{if(time>=duration)setTime(0);setPlaying(!playing)}}>{playing?'Pause':'Play'}</button><label><span className="folio-eyebrow">{Math.round(time)} / {duration} ms</span><input aria-label="Replay time" type="range" min="0" max={duration} step="1" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}}/></label></div><ol className={s.events}>{replayResult.events.map(event=><li key={event.id} data-active={time>=event.atMs}><time>{event.atMs}ms</time><span><small>{names[event.strategy]}{event.kind==='violation'?' / REQUIREMENT MISSED':''}</small>{event.message}</span></li>)}</ol><p className={s.notice}>{notice}</p></section>}
   </section>
  </div>
  <section className={s.guide}><div><span className="folio-eyebrow">A GUIDE, GROUNDED IN THE EXPERIMENT</span><h2>Ask about the trade-off.</h2><p>{replay?'The guide is explaining your replay and its saved requirements.':'The guide explains the current comparison and its requirements.'} The experiment runs locally, even when an AI provider is unavailable.</p></div><form onSubmit={ask}><label htmlFor="proof-question">What would you like to understand?</label><div><input id="proof-question" maxLength={600} value={question} disabled={busy} onChange={e=>{setQuestion(e.target.value);setAnswer('')}} placeholder="Why doesn’t fast + verified work?" required/><button className="folio-btn" data-variant="primary" disabled={busy||!question.trim()}>{busy?'Thinking…':'Ask'}<Icon name="arrow"/></button></div>{answer&&<div className={s.answer} role="status"><small>{guideMode}</small><p>{answer}</p><a href={replay?'#proof-replay':'#result:cache-first'} onClick={()=>setStep(replay?2:1)}>See the {replay?'replay':'comparison'} evidence ↑</a></div>}</form></section>
  <p className={s.scope} id="source:reading-board-v1">Experiment 001 models two fixed strategies, a saved reading board, and a successful synthetic response. It does not model outages, concurrent updates, or every production constraint. No employer system or private work is used.</p>
 </section>
}
